### PR TITLE
Add nodes-file-dir configuration

### PR DESCRIPTION
**Pull request by ohkinozomu**
close https://github.com/wind-c/comqtt/issues/106

### CODE REVIEW

**Comment by wind-c** [comment]
NodesFile is used to assist memberlist to discover nodes, and PeersFile is used to assist Raft to discover peers.
RaftDir stores all the data generated during raft running, so there is no need to put NodesFile in the RaftDir directory.

**Comment by wind-c** [comment]
NodesFile is used to assist memberlist to discover nodes, and PeersFile is used to assist Raft to discover peers.
RaftDir stores all the data generated during raft running, so there is no need to put NodesFile in the RaftDir directory.

**Comment by ohkinozomu** [comment]
Understood.
I have updated the pull request to make `NodesFileDir` configurable.
This change should be helpful for other comqtt users as well.
What do you think?

**Comment by wind-c** [comment]
Ok

**Pull request merged**
