### PR TITLE
Postgresql auth add bcrypt pw hashing

### PR DESCRIPTION
**Pull request by asbjorn**
I really don't like storing passwords as plain text in db :)
Also added a section in the README.md file to help users create the SQL tables and also creating hashed versions of the MQTT client passwords.

### CODE REVIEW

**Comment by wind-c** [comment]
I'm a big proponent of hashing passwords.

**Comment by wind-c** [comment]
There are several problems with your PR:
1.  Build failed
2. There should also be go bcrypt snippet in the README file
3.  Have redundant "if err! = nil"

Run go build ./...
go: downloading golang.org/x/crypto v0.0.0-20220622213112-05595931fe9d
go: updates to go.mod needed; to update it:
	go mod tidy
Error: Process completed with exit code 1.

**Comment by asbjorn** [comment]
Hi @wind-c!

Thanks for the feedback - it seems that I forgot the `go mod tidy` and the redundant iferr checks. There should also be a section in the README file. Also added a link from bcrypt to its corresponding Wikipedia article.

**Comment by wind-c** [comment]
good job

**Pull request merged**
